"""Project scaffolding and wizard for creating new SLR triage projects."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

from .presets import LEVEL_PRESETS, generate_config

logger = logging.getLogger(__name__)


@dataclass
class ProjectDefinition:
    """Definition of a new fastSLR project."""

    name: str
    description: str
    blocks: list[dict] = field(default_factory=list)
    preset: str = "standard"
    custom_preset: dict | None = None
    output_dir: Path = field(default_factory=lambda: Path("."))


def create_project(definition: ProjectDefinition) -> Path:
    """Create a new fastSLR project directory with template files."""
    project_dir = definition.output_dir / definition.name
    project_dir.mkdir(parents=True, exist_ok=True)

    config = generate_config(
        definition.preset,
        definition.blocks,
        custom_preset=definition.custom_preset,
    )

    generate_config_json(config, project_dir / "config.json")
    generate_terms_template(definition.blocks, definition.preset, project_dir / "terms.csv")
    generate_project_readme(definition, project_dir / "README.md")

    (project_dir / "data").mkdir(exist_ok=True)
    (project_dir / "output").mkdir(exist_ok=True)

    logger.info("Project created at %s", project_dir)
    return project_dir


def generate_config_json(config: dict, output_path: Path) -> None:
    """Write the project configuration JSON."""
    output_path.write_text(
        json.dumps(config, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )


def generate_terms_template(
    blocks: list[dict],
    preset: str,
    output_path: Path,
) -> None:
    """Generate a terms CSV template with example rows for each block."""
    preset_info = LEVEL_PRESETS.get(preset, LEVEL_PRESETS["standard"])
    max_level = preset_info["level_count"]

    lines = ["block;kind;term;level;section_scope;is_regex;normalization_type;normalization_target"]

    # GLOBAL block examples
    lines.append("GLOBAL;anti;systematic review;;any;0;;")
    lines.append("GLOBAL;anti;literature review;;any;0;;")
    lines.append("GLOBAL;flag;case study;;any;0;;")

    for block in blocks:
        name = block["name"]
        label = block.get("label", name)
        lines.append(f"# --- {label} ({name}) ---")
        for lvl in range(1, max_level + 1):
            lines.append(f"{name};pos;example_term_level_{lvl};{lvl};any;0;;")
        lines.append(f"{name};anti;example_exclusion;;any;0;;")
        lines.append(f"{name};flag;example_flag;;any;0;;")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_project_readme(definition: ProjectDefinition, output_path: Path) -> None:
    """Generate a README.md for the new project."""
    blocks_list = "\n".join(
        f"- **{b['name']}**: {b.get('label', b['name'])}" for b in definition.blocks
    )

    content = f"""# {definition.name}

{definition.description}

## Thematic Blocks

{blocks_list}

## Level Preset: {definition.preset}

## Quick Start

1. Edit `terms.csv` with your domain-specific terms
2. Place your corpus CSV in `data/`
3. Run:

```bash
fastslr run -i data/your_corpus.csv -t terms.csv -c config.json -o output/results.xlsx
```

## Pilot Mode (calibration)

```bash
fastslr pilot -i data/your_corpus.csv -t terms.csv -c config.json -n 50 --seed 42
```

## Coverage Report

```bash
fastslr report -i output/results.xlsx -t terms.csv -c config.json
```

---
Generated by [FastSLR](https://github.com/Leonardo/fastslr)
"""
    output_path.write_text(content, encoding="utf-8")


def run_wizard() -> ProjectDefinition:
    """Interactive wizard for creating a new project."""
    print("\n  FastSLR - New Project Wizard")
    print("  " + "=" * 40 + "\n")

    name = input("  Project name (alphanumeric + underscores): ").strip()
    if not name:
        name = "my_slr_project"
    name = name.replace(" ", "_").lower()

    description = input("  Domain description: ").strip()
    if not description:
        description = f"SLR triage project: {name}"

    n_blocks_str = input("  Number of thematic blocks (2-10) [3]: ").strip()
    n_blocks = int(n_blocks_str) if n_blocks_str else 3
    n_blocks = max(2, min(10, n_blocks))

    blocks: list[dict] = []
    for i in range(1, n_blocks + 1):
        print(f"\n  Block {i}:")
        bname = input(f"    Short name (e.g. CTX, TECH): ").strip().upper()
        if not bname:
            bname = f"B{i}"
        blabel = input(f"    Label (e.g. Context): ").strip()
        if not blabel:
            blabel = bname
        blocks.append({"name": bname, "label": blabel})

    print("\n  Level presets:")
    for key, info in LEVEL_PRESETS.items():
        print(f"    - {key}: {info['description']}")
    preset = input("  Choose preset [standard]: ").strip().lower()
    if preset not in LEVEL_PRESETS:
        preset = "standard"

    output_dir_str = input(f"  Output directory [.]: ").strip()
    output_dir = Path(output_dir_str) if output_dir_str else Path(".")

    return ProjectDefinition(
        name=name,
        description=description,
        blocks=blocks,
        preset=preset,
        output_dir=output_dir,
    )


__all__ = [
    "ProjectDefinition",
    "create_project",
    "generate_config_json",
    "generate_terms_template",
    "generate_project_readme",
    "run_wizard",
]
